"""
config.py
=========
ค่า config ทั้งหมดอยู่ที่นี่
REPLACE: API_URL เมื่อ deploy ขึ้น cloud
"""
import requests

API = "https://rogersurf-trump-signal-api-v2.hf.space"

data = requests.get(f"{API}/predict/latest").json()
>>>>>>> backup/stable-working

TIMEZONES = {
    "UTC":               0,
    "Bangkok (UTC+7)":   7,
    "Beijing (UTC+8)":   8,
    "New York (UTC-4)": -4,
    "London (UTC+1)":    1,
    "Copenhagen (UTC+2)": 2,
}

CATEGORY_COLORS = {
    "Threatening intl.":    "#E24B4A",
    "Attacking opposition": "#D85A30",
    "Self-promotion":       "#378ADD",
    "Enacting non-agg.":    "#1D9E75",
    "Praising/endorsing":   "#639922",
    "De-escalating":        "#7F77DD",
    "Other":                "#888780",
}

SENTIMENT_COLORS = {
    "POSITIVE": "#1D9E75",
    "NEGATIVE": "#E24B4A",
    "NEUTRAL":  "#888780",
}

INDEX_OPTIONS = {
    "sp500": "S&P 500",
    "qqq":   "QQQ (Nasdaq 100)",
    "djt":   "DJT (Trump Media)",
    "gld":   "GLD (Gold)",
    "tlt":   "TLT (US Bonds)",
    "lmt":   "LMT (Lockheed Martin)",
    "uso":   "USO (Oil)",
    "ibit":  "IBIT (Bitcoin ETF)",
    "uup":   "UUP (US Dollar)",
    "war":   "WAR ETF",
    "dia":   "DIA (Dow Jones)",
    "fxi":   "FXI (China ETF)",
    "xlv":   "XLV (Health Care)",
    "xli":   "XLI (Industrials)",
    "eww":   "EWW (Mexico ETF)",
    "vgk":   "VGK (Europe ETF)",
}

# ── i18n ──────────────────────────────────────────────────────────────────────
TRANSLATIONS = {
    "English": {
        "app_title":       "TrumpSignal",
        "tagline":         "Political signal analyzer — Trump Truth Social",
        "nav_user":        "User dashboard",
        "nav_dev":         "Developer dashboard",
        "daily_feed":      "Daily feed",
        "topics":          "Topic breakdown",
        "market":          "Market impact",
        "geo":             "Geopolitical",
        "qa":              "Q&A",
        "select_date":     "From",
        "to":              "To",
        "select_index":    "Stock index",
        "days_shown":      "Days shown",
        "period":          "Period",
        "timezone":        "Timezone",
        "language":        "Language",
        "dashboard":       "Dashboard",
        "search_btn":      "Search",
        "ask_placeholder": "e.g. He mentioned Iran, I have a business there — how does this affect me?",
        "match":           "Match",
        "sentiment":       "Sentiment",
        "category":        "Category",
        "engagement":      "Engagement",
        "likes":           "likes",
        "shares":          "shares",
        "replies":         "replies",
        "sp500_after":     "S&P 5min after",
        "click_post":      "Click any post to see full impact analysis",
        "post_detail":     "Impact analysis",
        "post_mentions":   "Key topics detected",
        "post_effects":    "What this could affect",
        "interp":          "Interpretation",
        "api_online":      "API online",
        "api_offline":     "API offline — showing mock data",
        "posts_today":     "Posts today",
        "total_posts":     "Total posts",
        "last_run":        "Last pipeline run",
        "pipeline_status": "Pipeline status",
        "artifact_log":    "Artifact log",
        "raw_data":        "Raw data preview",
        "download_csv":    "Download CSV",
        "mock_notice":     "Mock data mode — replace with real API",
        "no_results":      "No results found",
        "top_matches":     "Top matches",
        "week":            "Week",
        "month":           "Month",
        "year":            "Year",
        "all_healthy":     "All pipeline stages healthy",
        "error_detected":  "Pipeline error detected",
    },
    "Thai": {
        "app_title":       "TrumpSignal",
        "tagline":         "วิเคราะห์สัญญาณการเมือง — Trump Truth Social",
        "nav_user":        "หน้าผู้ใช้",
        "nav_dev":         "หน้านักพัฒนา",
        "daily_feed":      "โพสต์รายวัน",
        "topics":          "สัดส่วนหัวข้อ",
        "market":          "ผลกระทบตลาด",
        "geo":             "ภูมิรัฐศาสตร์",
        "qa":              "ถาม-ตอบ",
        "select_date":     "จาก",
        "to":              "ถึง",
        "select_index":    "ดัชนีหุ้น",
        "days_shown":      "จำนวนวัน",
        "period":          "ช่วงเวลา",
        "timezone":        "เขตเวลา",
        "language":        "ภาษา",
        "dashboard":       "แดชบอร์ด",
        "search_btn":      "ค้นหา",
        "ask_placeholder": "เช่น Trump พูดถึงอิหร่าน ฉันมีธุรกิจที่นั่น จะกระทบยังไง?",
        "match":           "ความเหมือน",
        "sentiment":       "ความรู้สึก",
        "category":        "หมวดหมู่",
        "engagement":      "Engagement",
        "likes":           "ไลค์",
        "shares":          "แชร์",
        "replies":         "ตอบกลับ",
        "sp500_after":     "S&P หลัง 5 นาที",
        "click_post":      "คลิกโพสต์เพื่อดูการวิเคราะห์ผลกระทบ",
        "post_detail":     "วิเคราะห์ผลกระทบ",
        "post_mentions":   "หัวข้อที่ตรวจพบ",
        "post_effects":    "อะไรที่อาจได้รับผลกระทบ",
        "interp":          "การตีความ",
        "api_online":      "API เชื่อมต่อแล้ว",
        "api_offline":     "API ออฟไลน์ — แสดงข้อมูลจำลอง",
        "posts_today":     "โพสต์วันนี้",
        "total_posts":     "โพสต์ทั้งหมด",
        "last_run":        "รันล่าสุด",
        "pipeline_status": "สถานะระบบ",
        "artifact_log":    "ประวัติการรัน",
        "raw_data":        "ดูข้อมูล raw",
        "download_csv":    "ดาวน์โหลด CSV",
        "mock_notice":     "โหมดข้อมูลจำลอง — เชื่อมต่อ API จริงเพื่อใช้งาน",
        "no_results":      "ไม่พบผลลัพธ์",
        "top_matches":     "ผลลัพธ์ที่ใกล้เคียง",
        "week":            "สัปดาห์",
        "month":           "เดือน",
        "year":            "ปี",
        "all_healthy":     "ระบบทุกส่วนทำงานปกติ",
        "error_detected":  "พบข้อผิดพลาดใน pipeline",
    },
    "Chinese": {
        "app_title":       "TrumpSignal",
        "tagline":         "政治信号分析器 — 特朗普 Truth Social",
        "nav_user":        "用户面板",
        "nav_dev":         "开发者面板",
        "daily_feed":      "每日动态",
        "topics":          "话题分布",
        "market":          "市场影响",
        "geo":             "地缘政治",
        "qa":              "问答",
        "select_date":     "从",
        "to":              "至",
        "select_index":    "股票指数",
        "days_shown":      "显示天数",
        "period":          "时间段",
        "timezone":        "时区",
        "language":        "语言",
        "dashboard":       "面板",
        "search_btn":      "搜索",
        "ask_placeholder": "例如：他提到了伊朗，我在那里有业务，会有什么影响？",
        "match":           "匹配度",
        "sentiment":       "情感",
        "category":        "类别",
        "engagement":      "互动量",
        "likes":           "点赞",
        "shares":          "转发",
        "replies":         "回复",
        "sp500_after":     "标普5分钟后",
        "click_post":      "点击帖子查看完整影响分析",
        "post_detail":     "影响分析",
        "post_mentions":   "检测到的关键话题",
        "post_effects":    "可能影响的方面",
        "interp":          "解读",
        "api_online":      "API 已连接",
        "api_offline":     "API 离线 — 显示模拟数据",
        "posts_today":     "今日推文",
        "total_posts":     "总推文数",
        "last_run":        "最近运行",
        "pipeline_status": "系统状态",
        "artifact_log":    "运行记录",
        "raw_data":        "原始数据预览",
        "download_csv":    "下载 CSV",
        "mock_notice":     "模拟数据模式 — 连接真实 API 以使用",
        "no_results":      "未找到结果",
        "top_matches":     "最佳匹配",
        "week":            "周",
        "month":           "月",
        "year":            "年",
        "all_healthy":     "所有管道阶段正常",
        "error_detected":  "检测到管道错误",
    },
}
