events {}

http {
    server {
        listen 7860;

        # API
        location /api/ {
            proxy_pass http://127.0.0.1:8000/;
        }

        location /docs {
            proxy_pass http://127.0.0.1:8000/docs;
        }

        location /openapi.json {
            proxy_pass http://127.0.0.1:8000/openapi.json;
        }

        location /health {
            proxy_pass http://127.0.0.1:8000/health;
        }

        # FRONTEND
        location / {
            proxy_pass http://127.0.0.1:8501/;
        }
    }
}